name: super_home_member
description: A new Flutter project.

version: 1.0.7+25

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.1.1
  cloud_firestore: ^4.1.0
  carousel_slider: ^4.1.1
  get_storage: ^2.0.3
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  pdf: ^3.8.2
  image_picker: ^0.8.5+3
  open_file: ^3.2.1
  month_picker_dialog: ^0.4.0
  gif_view: ^0.2.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.1
  introduction_screen: ^3.0.1
  new_version_plus:
  awesome_notifications:
  flutter_barcode_scanner: ^2.0.0
  flutter_rating_bar: ^4.0.1
  permission_handler: ^10.0.1
  wifi_iot:
  workmanager: ^0.5.1
  contacts_service: ^0.6.3
  email_validator: '^2.1.16'
  email_validator_flutter: "^1.0.0"
  fast_contacts: ^3.0.3
  dio: ^5.3.2
  wifi_scan: ^0.4.0+2
  app_settings: ^5.0.0
  connectivity_plus: ^4.0.2
  location: ^5.0.3
  webview_flutter: ^4.2.4
  #  get_it: ^7.6.4
  webview_dart: ^1.0.1
  #  flutter_webview_plugin: ^0.4.0
  internet_connection_checker: ^1.0.0+1
  js: ^0.6.2
  locator: ^0.0.0-dev.2
  connectivity: ^3.0.6
  flutter_offline: ^3.0.0
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  stockfish: ^1.4.0
  freezed_annotation: ^2.4.1
  get_it: ^7.2.0
  flame: ^1.10.1
  flame_audio: ^2.1.3
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
#  data_connection_checker: 0.1.1
#  webview_flutter: ^0.3.3

dev_dependencies:
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/super-home-logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/gif/
    - assets/intro/
#    - assets/tv/
    - assets/
    - assets/images/figures/black/
    - assets/images/figures/white/
    - images/


#  fonts:
#    - family: Jura
#      fonts:
#        - asset: assets2/font2/Jura-VariableFont_wght.ttf
#    - family: CeraProBold
#      fonts:
#        - asset: fonts/CeraPro-bold.ttf
#          style: normal
#    - family: CeraProMedium
#      fonts:
#        - asset: fonts/CeraProMedium.ttf
#          style: normal
#
